<?php
/**
 * Animals PublicSearch Request Test
 *
 * @package RescueGroups
 * @subpackage Tests
 * @author SourceGenerator
 */
namespace RescueGroups\Tests\Requests\Objects\Animals\PublicSearch;

class PublicSearchTest extends \PHPUnit\Framework\TestCase
{
    use \RescueGroups\Tests\Traits\APISetup;

    /**
     * Test Query
     */
    public function testQuery()
    {
        $this->apiLogin();

        $query = new \RescueGroups\Requests\Objects\Animals\PublicSearch();

        
        $query->setAnimalID("animalID");
        $query->setAnimalOrgID("animalOrgID");
        $query->setAnimalActivityLevel("animalActivityLevel");
        $query->setAnimalAdoptedDate("animalAdoptedDate");
        $query->setAnimalAdoptionFee("animalAdoptionFee");
        $query->setAnimalAgeString("animalAgeString");
        $query->setAnimalAltered("animalAltered");
        $query->setAnimalAvailableDate("animalAvailableDate");
        $query->setAnimalBirthdate("animalBirthdate");
        $query->setAnimalBirthdateExact("animalBirthdateExact");
        $query->setAnimalBreed("animalBreed");
        $query->setAnimalCoatLength("animalCoatLength");
        $query->setAnimalColor("animalColor");
        $query->setAnimalColorID("animalColorID");
        $query->setAnimalColorDetails("animalColorDetails");
        $query->setAnimalCourtesy("animalCourtesy");
        $query->setAnimalDeclawed("animalDeclawed");
        $query->setAnimalDescription("animalDescription");
        $query->setAnimalDescriptionPlain("animalDescriptionPlain");
        $query->setAnimalDistinguishingMarks("animalDistinguishingMarks");
        $query->setAnimalEarType("animalEarType");
        $query->setAnimalEnergyLevel("animalEnergyLevel");
        $query->setAnimalExerciseNeeds("animalExerciseNeeds");
        $query->setAnimalEyeColor("animalEyeColor");
        $query->setAnimalFence("animalFence");
        $query->setAnimalFound("animalFound");
        $query->setAnimalFoundDate("animalFoundDate");
        $query->setAnimalFoundPostalcode("animalFoundPostalcode");
        $query->setAnimalGeneralAge("animalGeneralAge");
        $query->setAnimalGeneralSizePotential("animalGeneralSizePotential");
        $query->setAnimalGroomingNeeds("animalGroomingNeeds");
        $query->setAnimalHousetrained("animalHousetrained");
        $query->setAnimalIndoorOutdoor("animalIndoorOutdoor");
        $query->setAnimalKillDate("animalKillDate");
        $query->setAnimalKillReason("animalKillReason");
        $query->setAnimalLocation("animalLocation");
        $query->setAnimalLocationCoordinates("animalLocationCoordinates");
        $query->setAnimalLocationDistance("animalLocationDistance");
        $query->setAnimalLocationCitystate("animalLocationCitystate");
        $query->setAnimalLocationState("animalLocationState");
        $query->setAnimalMicrochipped("animalMicrochipped");
        $query->setAnimalMixedBreed("animalMixedBreed");
        $query->setAnimalName("animalName");
        $query->setAnimalSpecialneeds("animalSpecialneeds");
        $query->setAnimalSpecialneedsDescription("animalSpecialneedsDescription");
        $query->setAnimalNeedsFoster("animalNeedsFoster");
        $query->setAnimalNewPeople("animalNewPeople");
        $query->setAnimalNotHousetrainedReason("animalNotHousetrainedReason");
        $query->setAnimalObedienceTraining("animalObedienceTraining");
        $query->setAnimalOKWithAdults("animalOKWithAdults");
        $query->setAnimalOKWithCats("animalOKWithCats");
        $query->setAnimalOKWithDogs("animalOKWithDogs");
        $query->setAnimalOKWithKids("animalOKWithKids");
        $query->setAnimalOwnerExperience("animalOwnerExperience");
        $query->setAnimalPattern("animalPattern");
        $query->setAnimalPatternID("animalPatternID");
        $query->setAnimalAdoptionPending("animalAdoptionPending");
        $query->setAnimalPrimaryBreed("animalPrimaryBreed");
        $query->setAnimalPrimaryBreedID("animalPrimaryBreedID");
        $query->setAnimalRescueID("animalRescueID");
        $query->setAnimalSearchString("animalSearchString");
        $query->setAnimalSecondaryBreed("animalSecondaryBreed");
        $query->setAnimalSecondaryBreedID("animalSecondaryBreedID");
        $query->setAnimalSex("animalSex");
        $query->setAnimalShedding("animalShedding");
        $query->setAnimalSizeCurrent("animalSizeCurrent");
        $query->setAnimalSizePotential("animalSizePotential");
        $query->setAnimalSizeUOM("animalSizeUOM");
        $query->setAnimalSpecies("animalSpecies");
        $query->setAnimalSpeciesID("animalSpeciesID");
        $query->setAnimalSponsorable("animalSponsorable");
        $query->setAnimalSponsors("animalSponsors");
        $query->setAnimalSponsorshipDetails("animalSponsorshipDetails");
        $query->setAnimalSponsorshipMinimum("animalSponsorshipMinimum");
        $query->setAnimalStatus("animalStatus");
        $query->setAnimalStatusID("animalStatusID");
        $query->setAnimalSummary("animalSummary");
        $query->setAnimalTailType("animalTailType");
        $query->setAnimalThumbnailUrl("animalThumbnailUrl");
        $query->setAnimalUptodate("animalUptodate");
        $query->setAnimalUpdatedDate("animalUpdatedDate");
        $query->setAnimalUrl("animalUrl");
        $query->setAnimalVocal("animalVocal");
        $query->setAnimalYardRequired("animalYardRequired");
        $query->setAnimalAffectionate("animalAffectionate");
        $query->setAnimalApartment("animalApartment");
        $query->setAnimalCratetrained("animalCratetrained");
        $query->setAnimalDrools("animalDrools");
        $query->setAnimalEagerToPlease("animalEagerToPlease");
        $query->setAnimalEscapes("animalEscapes");
        $query->setAnimalEventempered("animalEventempered");
        $query->setAnimalFetches("animalFetches");
        $query->setAnimalGentle("animalGentle");
        $query->setAnimalGoodInCar("animalGoodInCar");
        $query->setAnimalGoofy("animalGoofy");
        $query->setAnimalHasAllergies("animalHasAllergies");
        $query->setAnimalHearingImpaired("animalHearingImpaired");
        $query->setAnimalHypoallergenic("animalHypoallergenic");
        $query->setAnimalIndependent("animalIndependent");
        $query->setAnimalIntelligent("animalIntelligent");
        $query->setAnimalLap("animalLap");
        $query->setAnimalLeashtrained("animalLeashtrained");
        $query->setAnimalNeedsCompanionAnimal("animalNeedsCompanionAnimal");
        $query->setAnimalNoCold("animalNoCold");
        $query->setAnimalNoFemaleDogs("animalNoFemaleDogs");
        $query->setAnimalNoHeat("animalNoHeat");
        $query->setAnimalNoLargeDogs("animalNoLargeDogs");
        $query->setAnimalNoMaleDogs("animalNoMaleDogs");
        $query->setAnimalNoSmallDogs("animalNoSmallDogs");
        $query->setAnimalObedient("animalObedient");
        $query->setAnimalOKForSeniors("animalOKForSeniors");
        $query->setAnimalOKWithFarmAnimals("animalOKWithFarmAnimals");
        $query->setAnimalOlderKidsOnly("animalOlderKidsOnly");
        $query->setAnimalOngoingMedical("animalOngoingMedical");
        $query->setAnimalPlayful("animalPlayful");
        $query->setAnimalPlaysToys("animalPlaysToys");
        $query->setAnimalPredatory("animalPredatory");
        $query->setAnimalProtective("animalProtective");
        $query->setAnimalSightImpaired("animalSightImpaired");
        $query->setAnimalSkittish("animalSkittish");
        $query->setAnimalSpecialDiet("animalSpecialDiet");
        $query->setAnimalSwims("animalSwims");
        $query->setAnimalTimid("animalTimid");
        $query->setFosterEmail("fosterEmail");
        $query->setFosterFirstname("fosterFirstname");
        $query->setFosterLastname("fosterLastname");
        $query->setFosterName("fosterName");
        $query->setFosterPhoneCell("fosterPhoneCell");
        $query->setFosterPhoneHome("fosterPhoneHome");
        $query->setFosterSalutation("fosterSalutation");
        $query->setLocationAddress("locationAddress");
        $query->setLocationCity("locationCity");
        $query->setLocationCountry("locationCountry");
        $query->setLocationUrl("locationUrl");
        $query->setLocationName("locationName");
        $query->setLocationPhone("locationPhone");
        $query->setLocationState("locationState");
        $query->setLocationPostalcode("locationPostalcode");
        $query->setAnimalPictures("animalPictures");
        $query->setAnimalVideos("animalVideos");
        $query->setAnimalVideoUrls("animalVideoUrls");

        $data = $this->api->getPostObject($query);

        
        $this->assertEquals("animals", $data["objectType"]);

        $this->assertEquals("publicSearch", $data["objectAction"]);

        $this->assertEquals("animalID", $data["animalID"]);
        $this->assertEquals("animalOrgID", $data["animalOrgID"]);
        $this->assertEquals("animalActivityLevel", $data["animalActivityLevel"]);
        $this->assertEquals("animalAdoptedDate", $data["animalAdoptedDate"]);
        $this->assertEquals("animalAdoptionFee", $data["animalAdoptionFee"]);
        $this->assertEquals("animalAgeString", $data["animalAgeString"]);
        $this->assertEquals("animalAltered", $data["animalAltered"]);
        $this->assertEquals("animalAvailableDate", $data["animalAvailableDate"]);
        $this->assertEquals("animalBirthdate", $data["animalBirthdate"]);
        $this->assertEquals("animalBirthdateExact", $data["animalBirthdateExact"]);
        $this->assertEquals("animalBreed", $data["animalBreed"]);
        $this->assertEquals("animalCoatLength", $data["animalCoatLength"]);
        $this->assertEquals("animalColor", $data["animalColor"]);
        $this->assertEquals("animalColorID", $data["animalColorID"]);
        $this->assertEquals("animalColorDetails", $data["animalColorDetails"]);
        $this->assertEquals("animalCourtesy", $data["animalCourtesy"]);
        $this->assertEquals("animalDeclawed", $data["animalDeclawed"]);
        $this->assertEquals("animalDescription", $data["animalDescription"]);
        $this->assertEquals("animalDescriptionPlain", $data["animalDescriptionPlain"]);
        $this->assertEquals("animalDistinguishingMarks", $data["animalDistinguishingMarks"]);
        $this->assertEquals("animalEarType", $data["animalEarType"]);
        $this->assertEquals("animalEnergyLevel", $data["animalEnergyLevel"]);
        $this->assertEquals("animalExerciseNeeds", $data["animalExerciseNeeds"]);
        $this->assertEquals("animalEyeColor", $data["animalEyeColor"]);
        $this->assertEquals("animalFence", $data["animalFence"]);
        $this->assertEquals("animalFound", $data["animalFound"]);
        $this->assertEquals("animalFoundDate", $data["animalFoundDate"]);
        $this->assertEquals("animalFoundPostalcode", $data["animalFoundPostalcode"]);
        $this->assertEquals("animalGeneralAge", $data["animalGeneralAge"]);
        $this->assertEquals("animalGeneralSizePotential", $data["animalGeneralSizePotential"]);
        $this->assertEquals("animalGroomingNeeds", $data["animalGroomingNeeds"]);
        $this->assertEquals("animalHousetrained", $data["animalHousetrained"]);
        $this->assertEquals("animalIndoorOutdoor", $data["animalIndoorOutdoor"]);
        $this->assertEquals("animalKillDate", $data["animalKillDate"]);
        $this->assertEquals("animalKillReason", $data["animalKillReason"]);
        $this->assertEquals("animalLocation", $data["animalLocation"]);
        $this->assertEquals("animalLocationCoordinates", $data["animalLocationCoordinates"]);
        $this->assertEquals("animalLocationDistance", $data["animalLocationDistance"]);
        $this->assertEquals("animalLocationCitystate", $data["animalLocationCitystate"]);
        $this->assertEquals("animalLocationState", $data["animalLocationState"]);
        $this->assertEquals("animalMicrochipped", $data["animalMicrochipped"]);
        $this->assertEquals("animalMixedBreed", $data["animalMixedBreed"]);
        $this->assertEquals("animalName", $data["animalName"]);
        $this->assertEquals("animalSpecialneeds", $data["animalSpecialneeds"]);
        $this->assertEquals("animalSpecialneedsDescription", $data["animalSpecialneedsDescription"]);
        $this->assertEquals("animalNeedsFoster", $data["animalNeedsFoster"]);
        $this->assertEquals("animalNewPeople", $data["animalNewPeople"]);
        $this->assertEquals("animalNotHousetrainedReason", $data["animalNotHousetrainedReason"]);
        $this->assertEquals("animalObedienceTraining", $data["animalObedienceTraining"]);
        $this->assertEquals("animalOKWithAdults", $data["animalOKWithAdults"]);
        $this->assertEquals("animalOKWithCats", $data["animalOKWithCats"]);
        $this->assertEquals("animalOKWithDogs", $data["animalOKWithDogs"]);
        $this->assertEquals("animalOKWithKids", $data["animalOKWithKids"]);
        $this->assertEquals("animalOwnerExperience", $data["animalOwnerExperience"]);
        $this->assertEquals("animalPattern", $data["animalPattern"]);
        $this->assertEquals("animalPatternID", $data["animalPatternID"]);
        $this->assertEquals("animalAdoptionPending", $data["animalAdoptionPending"]);
        $this->assertEquals("animalPrimaryBreed", $data["animalPrimaryBreed"]);
        $this->assertEquals("animalPrimaryBreedID", $data["animalPrimaryBreedID"]);
        $this->assertEquals("animalRescueID", $data["animalRescueID"]);
        $this->assertEquals("animalSearchString", $data["animalSearchString"]);
        $this->assertEquals("animalSecondaryBreed", $data["animalSecondaryBreed"]);
        $this->assertEquals("animalSecondaryBreedID", $data["animalSecondaryBreedID"]);
        $this->assertEquals("animalSex", $data["animalSex"]);
        $this->assertEquals("animalShedding", $data["animalShedding"]);
        $this->assertEquals("animalSizeCurrent", $data["animalSizeCurrent"]);
        $this->assertEquals("animalSizePotential", $data["animalSizePotential"]);
        $this->assertEquals("animalSizeUOM", $data["animalSizeUOM"]);
        $this->assertEquals("animalSpecies", $data["animalSpecies"]);
        $this->assertEquals("animalSpeciesID", $data["animalSpeciesID"]);
        $this->assertEquals("animalSponsorable", $data["animalSponsorable"]);
        $this->assertEquals("animalSponsors", $data["animalSponsors"]);
        $this->assertEquals("animalSponsorshipDetails", $data["animalSponsorshipDetails"]);
        $this->assertEquals("animalSponsorshipMinimum", $data["animalSponsorshipMinimum"]);
        $this->assertEquals("animalStatus", $data["animalStatus"]);
        $this->assertEquals("animalStatusID", $data["animalStatusID"]);
        $this->assertEquals("animalSummary", $data["animalSummary"]);
        $this->assertEquals("animalTailType", $data["animalTailType"]);
        $this->assertEquals("animalThumbnailUrl", $data["animalThumbnailUrl"]);
        $this->assertEquals("animalUptodate", $data["animalUptodate"]);
        $this->assertEquals("animalUpdatedDate", $data["animalUpdatedDate"]);
        $this->assertEquals("animalUrl", $data["animalUrl"]);
        $this->assertEquals("animalVocal", $data["animalVocal"]);
        $this->assertEquals("animalYardRequired", $data["animalYardRequired"]);
        $this->assertEquals("animalAffectionate", $data["animalAffectionate"]);
        $this->assertEquals("animalApartment", $data["animalApartment"]);
        $this->assertEquals("animalCratetrained", $data["animalCratetrained"]);
        $this->assertEquals("animalDrools", $data["animalDrools"]);
        $this->assertEquals("animalEagerToPlease", $data["animalEagerToPlease"]);
        $this->assertEquals("animalEscapes", $data["animalEscapes"]);
        $this->assertEquals("animalEventempered", $data["animalEventempered"]);
        $this->assertEquals("animalFetches", $data["animalFetches"]);
        $this->assertEquals("animalGentle", $data["animalGentle"]);
        $this->assertEquals("animalGoodInCar", $data["animalGoodInCar"]);
        $this->assertEquals("animalGoofy", $data["animalGoofy"]);
        $this->assertEquals("animalHasAllergies", $data["animalHasAllergies"]);
        $this->assertEquals("animalHearingImpaired", $data["animalHearingImpaired"]);
        $this->assertEquals("animalHypoallergenic", $data["animalHypoallergenic"]);
        $this->assertEquals("animalIndependent", $data["animalIndependent"]);
        $this->assertEquals("animalIntelligent", $data["animalIntelligent"]);
        $this->assertEquals("animalLap", $data["animalLap"]);
        $this->assertEquals("animalLeashtrained", $data["animalLeashtrained"]);
        $this->assertEquals("animalNeedsCompanionAnimal", $data["animalNeedsCompanionAnimal"]);
        $this->assertEquals("animalNoCold", $data["animalNoCold"]);
        $this->assertEquals("animalNoFemaleDogs", $data["animalNoFemaleDogs"]);
        $this->assertEquals("animalNoHeat", $data["animalNoHeat"]);
        $this->assertEquals("animalNoLargeDogs", $data["animalNoLargeDogs"]);
        $this->assertEquals("animalNoMaleDogs", $data["animalNoMaleDogs"]);
        $this->assertEquals("animalNoSmallDogs", $data["animalNoSmallDogs"]);
        $this->assertEquals("animalObedient", $data["animalObedient"]);
        $this->assertEquals("animalOKForSeniors", $data["animalOKForSeniors"]);
        $this->assertEquals("animalOKWithFarmAnimals", $data["animalOKWithFarmAnimals"]);
        $this->assertEquals("animalOlderKidsOnly", $data["animalOlderKidsOnly"]);
        $this->assertEquals("animalOngoingMedical", $data["animalOngoingMedical"]);
        $this->assertEquals("animalPlayful", $data["animalPlayful"]);
        $this->assertEquals("animalPlaysToys", $data["animalPlaysToys"]);
        $this->assertEquals("animalPredatory", $data["animalPredatory"]);
        $this->assertEquals("animalProtective", $data["animalProtective"]);
        $this->assertEquals("animalSightImpaired", $data["animalSightImpaired"]);
        $this->assertEquals("animalSkittish", $data["animalSkittish"]);
        $this->assertEquals("animalSpecialDiet", $data["animalSpecialDiet"]);
        $this->assertEquals("animalSwims", $data["animalSwims"]);
        $this->assertEquals("animalTimid", $data["animalTimid"]);
        $this->assertEquals("fosterEmail", $data["fosterEmail"]);
        $this->assertEquals("fosterFirstname", $data["fosterFirstname"]);
        $this->assertEquals("fosterLastname", $data["fosterLastname"]);
        $this->assertEquals("fosterName", $data["fosterName"]);
        $this->assertEquals("fosterPhoneCell", $data["fosterPhoneCell"]);
        $this->assertEquals("fosterPhoneHome", $data["fosterPhoneHome"]);
        $this->assertEquals("fosterSalutation", $data["fosterSalutation"]);
        $this->assertEquals("locationAddress", $data["locationAddress"]);
        $this->assertEquals("locationCity", $data["locationCity"]);
        $this->assertEquals("locationCountry", $data["locationCountry"]);
        $this->assertEquals("locationUrl", $data["locationUrl"]);
        $this->assertEquals("locationName", $data["locationName"]);
        $this->assertEquals("locationPhone", $data["locationPhone"]);
        $this->assertEquals("locationState", $data["locationState"]);
        $this->assertEquals("locationPostalcode", $data["locationPostalcode"]);
        $this->assertEquals("animalPictures", $data["animalPictures"]);
        $this->assertEquals("animalVideos", $data["animalVideos"]);
        $this->assertEquals("animalVideoUrls", $data["animalVideoUrls"]);
    }
}