<?php
/**
 * Animals publicSearch Request Test
 *
 * @package RescueGroups
 * @subpackage Tests
 * @author SourceGenerator
 */
namespace RescueGroups\Tests\Request\Objects\Animals;

class PublicSearchTest extends \PHPUnit\Framework\TestCase
{
    use \RescueGroups\Tests\Traits\APISetup;

    /**
     * Test Query
     */
    public function testQuery()
    {
        $this->apiLogin();

        $query = new \RescueGroups\Request\Objects\Animals\PublicSearch();
        $query
            ->setResultStart(33)
            ->setResultLimit(123)
            ->setResultSort('testSortValue')
            ->setResultOrder('ascending')
            ->addField('animalID')
            ->addField('animalOrgID')
            ->addField('animalActivityLevel')
            ->addField('animalAdoptedDate')
            ->addField('animalAdoptionFee')
            ->addField('animalAgeString')
            ->addField('animalAltered')
            ->addField('animalAvailableDate')
            ->addField('animalBirthdate')
            ->addField('animalBirthdateExact')
            ->addField('animalBreed')
            ->addField('animalCoatLength')
            ->addField('animalColor')
            ->addField('animalColorID')
            ->addField('animalColorDetails')
            ->addField('animalCourtesy')
            ->addField('animalDeclawed')
            ->addField('animalDescription')
            ->addField('animalDescriptionPlain')
            ->addField('animalDistinguishingMarks')
            ->addField('animalEarType')
            ->addField('animalEnergyLevel')
            ->addField('animalExerciseNeeds')
            ->addField('animalEyeColor')
            ->addField('animalFence')
            ->addField('animalFound')
            ->addField('animalFoundDate')
            ->addField('animalFoundPostalcode')
            ->addField('animalGeneralAge')
            ->addField('animalGeneralSizePotential')
            ->addField('animalGroomingNeeds')
            ->addField('animalHousetrained')
            ->addField('animalIndoorOutdoor')
            ->addField('animalKillDate')
            ->addField('animalKillReason')
            ->addField('animalLocation')
            ->addField('animalLocationCoordinates')
            ->addField('animalLocationDistance')
            ->addField('animalLocationCitystate')
            ->addField('animalLocationState')
            ->addField('animalMicrochipped')
            ->addField('animalMixedBreed')
            ->addField('animalName')
            ->addField('animalSpecialneeds')
            ->addField('animalSpecialneedsDescription')
            ->addField('animalNeedsFoster')
            ->addField('animalNewPeople')
            ->addField('animalNotHousetrainedReason')
            ->addField('animalObedienceTraining')
            ->addField('animalOKWithAdults')
            ->addField('animalOKWithCats')
            ->addField('animalOKWithDogs')
            ->addField('animalOKWithKids')
            ->addField('animalOwnerExperience')
            ->addField('animalPattern')
            ->addField('animalPatternID')
            ->addField('animalAdoptionPending')
            ->addField('animalPrimaryBreed')
            ->addField('animalPrimaryBreedID')
            ->addField('animalRescueID')
            ->addField('animalSearchString')
            ->addField('animalSecondaryBreed')
            ->addField('animalSecondaryBreedID')
            ->addField('animalSex')
            ->addField('animalShedding')
            ->addField('animalSizeCurrent')
            ->addField('animalSizePotential')
            ->addField('animalSizeUOM')
            ->addField('animalSpecies')
            ->addField('animalSpeciesID')
            ->addField('animalSponsorable')
            ->addField('animalSponsors')
            ->addField('animalSponsorshipDetails')
            ->addField('animalSponsorshipMinimum')
            ->addField('animalStatus')
            ->addField('animalStatusID')
            ->addField('animalSummary')
            ->addField('animalTailType')
            ->addField('animalThumbnailUrl')
            ->addField('animalUptodate')
            ->addField('animalUpdatedDate')
            ->addField('animalUrl')
            ->addField('animalVocal')
            ->addField('animalYardRequired')
            ->addField('animalAffectionate')
            ->addField('animalApartment')
            ->addField('animalCratetrained')
            ->addField('animalDrools')
            ->addField('animalEagerToPlease')
            ->addField('animalEscapes')
            ->addField('animalEventempered')
            ->addField('animalFetches')
            ->addField('animalGentle')
            ->addField('animalGoodInCar')
            ->addField('animalGoofy')
            ->addField('animalHasAllergies')
            ->addField('animalHearingImpaired')
            ->addField('animalHypoallergenic')
            ->addField('animalIndependent')
            ->addField('animalIntelligent')
            ->addField('animalLap')
            ->addField('animalLeashtrained')
            ->addField('animalNeedsCompanionAnimal')
            ->addField('animalNoCold')
            ->addField('animalNoFemaleDogs')
            ->addField('animalNoHeat')
            ->addField('animalNoLargeDogs')
            ->addField('animalNoMaleDogs')
            ->addField('animalNoSmallDogs')
            ->addField('animalObedient')
            ->addField('animalOKForSeniors')
            ->addField('animalOKWithFarmAnimals')
            ->addField('animalOlderKidsOnly')
            ->addField('animalOngoingMedical')
            ->addField('animalPlayful')
            ->addField('animalPlaysToys')
            ->addField('animalPredatory')
            ->addField('animalProtective')
            ->addField('animalSightImpaired')
            ->addField('animalSkittish')
            ->addField('animalSpecialDiet')
            ->addField('animalSwims')
            ->addField('animalTimid')
            ->addField('fosterEmail')
            ->addField('fosterFirstname')
            ->addField('fosterLastname')
            ->addField('fosterName')
            ->addField('fosterPhoneCell')
            ->addField('fosterPhoneHome')
            ->addField('fosterSalutation')
            ->addField('locationAddress')
            ->addField('locationCity')
            ->addField('locationCountry')
            ->addField('locationUrl')
            ->addField('locationName')
            ->addField('locationPhone')
            ->addField('locationState')
            ->addField('locationPostalcode')
            ->addField('animalPictures')
            ->addField('animalVideos')
            ->addField('animalVideoUrls')
            ->setCalculateFoundRows(true);

        $data = $this->api->getPostObject($query);

        $this->assertEquals('animals', $data['objectType']);
        $this->assertEquals('publicSearch', $data['objectAction']);
        $this->assertEquals(33, $data['search']->resultStart);
        $this->assertEquals(123, $data['search']->resultLimit);
        $this->assertEquals('testSortValue', $data['search']->resultSort);
        $this->assertEquals('ascending', $data['search']->resultOrder);
        $this->assertEquals('Yes', $data['search']->calcFoundRows);
        
        $translatedFields = [
            "animalID",
            "animalOrgID",
            "animalActivityLevel",
            "animalAdoptedDate",
            "animalAdoptionFee",
            "animalAgeString",
            "animalAltered",
            "animalAvailableDate",
            "animalBirthdate",
            "animalBirthdateExact",
            "animalBreed",
            "animalCoatLength",
            "animalColor",
            "animalColorID",
            "animalColorDetails",
            "animalCourtesy",
            "animalDeclawed",
            "animalDescription",
            "animalDescriptionPlain",
            "animalDistinguishingMarks",
            "animalEarType",
            "animalEnergyLevel",
            "animalExerciseNeeds",
            "animalEyeColor",
            "animalFence",
            "animalFound",
            "animalFoundDate",
            "animalFoundPostalcode",
            "animalGeneralAge",
            "animalGeneralSizePotential",
            "animalGroomingNeeds",
            "animalHousetrained",
            "animalIndoorOutdoor",
            "animalKillDate",
            "animalKillReason",
            "animalLocation",
            "animalLocationCoordinates",
            "animalLocationDistance",
            "animalLocationCitystate",
            "animalLocationState",
            "animalMicrochipped",
            "animalMixedBreed",
            "animalName",
            "animalSpecialneeds",
            "animalSpecialneedsDescription",
            "animalNeedsFoster",
            "animalNewPeople",
            "animalNotHousetrainedReason",
            "animalObedienceTraining",
            "animalOKWithAdults",
            "animalOKWithCats",
            "animalOKWithDogs",
            "animalOKWithKids",
            "animalOwnerExperience",
            "animalPattern",
            "animalPatternID",
            "animalAdoptionPending",
            "animalPrimaryBreed",
            "animalPrimaryBreedID",
            "animalRescueID",
            "animalSearchString",
            "animalSecondaryBreed",
            "animalSecondaryBreedID",
            "animalSex",
            "animalShedding",
            "animalSizeCurrent",
            "animalSizePotential",
            "animalSizeUOM",
            "animalSpecies",
            "animalSpeciesID",
            "animalSponsorable",
            "animalSponsors",
            "animalSponsorshipDetails",
            "animalSponsorshipMinimum",
            "animalStatus",
            "animalStatusID",
            "animalSummary",
            "animalTailType",
            "animalThumbnailUrl",
            "animalUptodate",
            "animalUpdatedDate",
            "animalUrl",
            "animalVocal",
            "animalYardRequired",
            "animalAffectionate",
            "animalApartment",
            "animalCratetrained",
            "animalDrools",
            "animalEagerToPlease",
            "animalEscapes",
            "animalEventempered",
            "animalFetches",
            "animalGentle",
            "animalGoodInCar",
            "animalGoofy",
            "animalHasAllergies",
            "animalHearingImpaired",
            "animalHypoallergenic",
            "animalIndependent",
            "animalIntelligent",
            "animalLap",
            "animalLeashtrained",
            "animalNeedsCompanionAnimal",
            "animalNoCold",
            "animalNoFemaleDogs",
            "animalNoHeat",
            "animalNoLargeDogs",
            "animalNoMaleDogs",
            "animalNoSmallDogs",
            "animalObedient",
            "animalOKForSeniors",
            "animalOKWithFarmAnimals",
            "animalOlderKidsOnly",
            "animalOngoingMedical",
            "animalPlayful",
            "animalPlaysToys",
            "animalPredatory",
            "animalProtective",
            "animalSightImpaired",
            "animalSkittish",
            "animalSpecialDiet",
            "animalSwims",
            "animalTimid",
            "fosterEmail",
            "fosterFirstname",
            "fosterLastname",
            "fosterName",
            "fosterPhoneCell",
            "fosterPhoneHome",
            "fosterSalutation",
            "locationAddress",
            "locationCity",
            "locationCountry",
            "locationUrl",
            "locationName",
            "locationPhone",
            "locationState",
            "locationPostalcode",
            "animalPictures",
            "animalVideos",
            "animalVideoUrls",
        ];

        $this->assertEquals($translatedFields, $data['search']->fields);
    }
}
