<?php
/**
 * Animals search Request Test
 *
 * @package RescueGroups
 * @subpackage Tests
 * @author SourceGenerator
 */
namespace RescueGroups\Tests\Request\Objects\Animals;

class SearchTest extends \PHPUnit\Framework\TestCase
{
    use \RescueGroups\Tests\Traits\APISetup;

    /**
     * Test Query
     */
    public function testQuery()
    {
        $this->apiLogin();

        $query = new \RescueGroups\Request\Objects\Animals\Search();
        $query
            ->setResultStart(33)
            ->setResultLimit(123)
            ->setResultSort('testSortValue')
            ->setResultOrder('ascending')
            ->addField('animalID')
            ->addField('animalActivityLevel')
            ->addField('animalAdoptedDate')
            ->addField('animalAdoptionFee')
            ->addField('animalAdoptionLead')
            ->addField('animalAdoptionLeadID')
            ->addField('animalAltered')
            ->addField('animalApplicationID')
            ->addField('animalAvailableDate')
            ->addField('animalBirthdate')
            ->addField('animalBirthdateExact')
            ->addField('animalBreed')
            ->addField('animalCoatLength')
            ->addField('animalColonyID')
            ->addField('animalColor')
            ->addField('animalColorID')
            ->addField('animalColorDetails')
            ->addField('animalCondition')
            ->addField('animalConditionID')
            ->addField('animalCost')
            ->addField('animalCourtesy')
            ->addField('animalCreatedDate')
            ->addField('animalCreatedBy')
            ->addField('animalCreatedByID')
            ->addField('animalCreatedTimeframe')
            ->addField('animalDaysInFoster')
            ->addField('animalDeclawed')
            ->addField('animalDescription')
            ->addField('animalDescriptionPlain')
            ->addField('animalDistinguishingMarks')
            ->addField('animalAllowExport')
            ->addField('animalEarType')
            ->addField('animalEnergyLevel')
            ->addField('animalExerciseNeeds')
            ->addField('animalEyeColor')
            ->addField('animalFence')
            ->addField('animalFosterID')
            ->addField('animalFound')
            ->addField('animalFoundDate')
            ->addField('animalFoundPostalcode')
            ->addField('animalGeneralAge')
            ->addField('animalGeneralSizePotential')
            ->addField('animalGroomingNeeds')
            ->addField('animalHighlightOrder')
            ->addField('animalHousetrained')
            ->addField('animalIndoorOutdoor')
            ->addField('animalIntakes')
            ->addField('animalInternalID')
            ->addField('animalKillDate')
            ->addField('animalKillReason')
            ->addField('animalUpdatedBy')
            ->addField('animalUpdatedByID')
            ->addField('animalUpdatedDate')
            ->addField('animalUpdatedTimeframe')
            ->addField('animalLocationID')
            ->addField('animalLocationPublic')
            ->addField('animalMicrochipped')
            ->addField('animalMicrochipNumber')
            ->addField('animalMicrochipVendor')
            ->addField('animalMixedBreed')
            ->addField('animalName')
            ->addField('animalSpecialneeds')
            ->addField('animalSpecialneedsDescription')
            ->addField('animalNeedsFoster')
            ->addField('animalNewPeople')
            ->addField('animalNotes')
            ->addField('animalNotHousetrainedReason')
            ->addField('animalObedienceTraining')
            ->addField('animalOKWithAdults')
            ->addField('animalOKWithCats')
            ->addField('animalOKWithDogs')
            ->addField('animalOKWithKids')
            ->addField('animalOpenIntakes')
            ->addField('animalOrigin')
            ->addField('animalOthernames')
            ->addField('animalOutcomes')
            ->addField('animalOwnerExperience')
            ->addField('animalOwnerID')
            ->addField('animalPattern')
            ->addField('animalPatternID')
            ->addField('animalAdoptionPending')
            ->addField('animalPrimaryBreed')
            ->addField('animalPrimaryBreedID')
            ->addField('animalReceivedDate')
            ->addField('animalRescueID')
            ->addField('animalSecondaryBreed')
            ->addField('animalSecondaryBreedID')
            ->addField('animalSex')
            ->addField('animalShared')
            ->addField('animalShedding')
            ->addField('animalSizeCurrent')
            ->addField('animalSizePotential')
            ->addField('animalSizeUOM')
            ->addField('animalSpecies')
            ->addField('animalSpeciesID')
            ->addField('animalSponsorable')
            ->addField('animalSponsors')
            ->addField('animalSponsorshipDetails')
            ->addField('animalSponsorshipMinimum')
            ->addField('animalStatus')
            ->addField('animalStatusID')
            ->addField('animalSummary')
            ->addField('animalTailType')
            ->addField('animalTransferredToID')
            ->addField('animalUptodate')
            ->addField('animalVocal')
            ->addField('animalYardRequired')
            ->addField('animalAffectionate')
            ->addField('animalApartment')
            ->addField('animalCratetrained')
            ->addField('animalDrools')
            ->addField('animalEagerToPlease')
            ->addField('animalEscapes')
            ->addField('animalEventempered')
            ->addField('animalFetches')
            ->addField('animalGentle')
            ->addField('animalGoodInCar')
            ->addField('animalGoofy')
            ->addField('animalHasAllergies')
            ->addField('animalHearingImpaired')
            ->addField('animalHypoallergenic')
            ->addField('animalIndependent')
            ->addField('animalIntelligent')
            ->addField('animalLap')
            ->addField('animalLeashtrained')
            ->addField('animalNeedsCompanionAnimal')
            ->addField('animalNoCold')
            ->addField('animalNoFemaleDogs')
            ->addField('animalNoHeat')
            ->addField('animalNoLargeDogs')
            ->addField('animalNoMaleDogs')
            ->addField('animalNoSmallDogs')
            ->addField('animalObedient')
            ->addField('animalOKForSeniors')
            ->addField('animalOKWithFarmAnimals')
            ->addField('animalOlderKidsOnly')
            ->addField('animalOngoingMedical')
            ->addField('animalPlayful')
            ->addField('animalPlaysToys')
            ->addField('animalPredatory')
            ->addField('animalProtective')
            ->addField('animalSightImpaired')
            ->addField('animalSkittish')
            ->addField('animalSpecialDiet')
            ->addField('animalSwims')
            ->addField('animalTimid')
            ->addField('ownerID')
            ->addField('ownerActive')
            ->addField('ownerAddress')
            ->addField('ownerBounces')
            ->addField('ownerCarrier')
            ->addField('ownerCity')
            ->addField('ownerComment')
            ->addField('ownerCompany')
            ->addField('ownerCountry')
            ->addField('ownerCounty')
            ->addField('ownerEmail')
            ->addField('ownerEmailAlt')
            ->addField('ownerEmailPager')
            ->addField('ownerFax')
            ->addField('ownerFirstname')
            ->addField('ownerLastname')
            ->addField('ownerName')
            ->addField('ownerPhoneCell')
            ->addField('ownerPhoneHome')
            ->addField('ownerPhoneWork')
            ->addField('ownerPhoneWorkExt')
            ->addField('ownerPlus4')
            ->addField('ownerReferredBy')
            ->addField('ownerSalutation')
            ->addField('ownerSendMail')
            ->addField('ownerState')
            ->addField('ownerTitle')
            ->addField('ownerPostalcode')
            ->addField('colonyAnimals')
            ->addField('colonyCaretakers')
            ->addField('colonyLocation')
            ->addField('colonyLocationID')
            ->addField('colonyName')
            ->addField('colonyRegisteredDate')
            ->addField('colonySpecificLocation')
            ->addField('fosterID')
            ->addField('fosterActive')
            ->addField('fosterAddress')
            ->addField('fosterBounces')
            ->addField('fosterCarrier')
            ->addField('fosterCity')
            ->addField('fosterComment')
            ->addField('fosterCompany')
            ->addField('fosterCountry')
            ->addField('fosterCounty')
            ->addField('fosterEmail')
            ->addField('fosterEmailAlt')
            ->addField('fosterEmailPager')
            ->addField('fosterFax')
            ->addField('fosterFirstname')
            ->addField('fosterLastname')
            ->addField('fosterName')
            ->addField('fosterPhoneCell')
            ->addField('fosterPhoneHome')
            ->addField('fosterPhoneWork')
            ->addField('fosterPhoneWorkExt')
            ->addField('fosterPlus4')
            ->addField('fosterReferredBy')
            ->addField('fosterSalutation')
            ->addField('fosterSendMail')
            ->addField('fosterState')
            ->addField('fosterTitle')
            ->addField('fosterPostalcode')
            ->addField('locationAddress')
            ->addField('locationAnimals')
            ->addField('locationCity')
            ->addField('locationColonies')
            ->addField('locationCountry')
            ->addField('locationUrl')
            ->addField('locationEvents')
            ->addField('locationMeetrequests')
            ->addField('locationName')
            ->addField('locationPhone')
            ->addField('locationState')
            ->addField('locationPostalcode')
            ->addField('submittedformID')
            ->addField('submittedformAnimalID')
            ->addField('submittedformAssignedToID')
            ->addField('submittedformCommentsCount')
            ->addField('submittedformCommentsInline')
            ->addField('submittedformCompletedDate')
            ->addField('submittedformFormName')
            ->addField('submittedformPending')
            ->addField('submittedformStatus')
            ->addField('submittedformStepsCount')
            ->addField('submitterID')
            ->addField('submitterActive')
            ->addField('submitterAddress')
            ->addField('submitterBounces')
            ->addField('submitterCarrier')
            ->addField('submitterCity')
            ->addField('submitterComment')
            ->addField('submitterCompany')
            ->addField('submitterCountry')
            ->addField('submitterCounty')
            ->addField('submitterEmail')
            ->addField('submitterEmailAlt')
            ->addField('submitterEmailPager')
            ->addField('submitterFax')
            ->addField('submitterFirstname')
            ->addField('submitterLastname')
            ->addField('submitterName')
            ->addField('submitterPhoneCell')
            ->addField('submitterPhoneHome')
            ->addField('submitterPhoneWork')
            ->addField('submitterPhoneWorkExt')
            ->addField('submitterPlus4')
            ->addField('submitterReferredBy')
            ->addField('submitterSalutation')
            ->addField('submitterSendMail')
            ->addField('submitterState')
            ->addField('submitterTitle')
            ->addField('submitterPostalcode')
            ->addField('transferredtoActive')
            ->addField('transferredtoAddress')
            ->addField('transferredtoBounces')
            ->addField('transferredtoCarrier')
            ->addField('transferredtoCity')
            ->addField('transferredtoComment')
            ->addField('transferredtoCompany')
            ->addField('transferredtoID')
            ->addField('transferredtoCountry')
            ->addField('transferredtoCounty')
            ->addField('transferredtoEmail')
            ->addField('transferredtoEmailAlt')
            ->addField('transferredtoEmailPager')
            ->addField('transferredtoFax')
            ->addField('transferredtoFirstname')
            ->addField('transferredtoLastname')
            ->addField('transferredtoName')
            ->addField('transferredtoPhoneCell')
            ->addField('transferredtoPhoneHome')
            ->addField('transferredtoPhoneWork')
            ->addField('transferredtoPhoneWorkExt')
            ->addField('transferredtoPlus4')
            ->addField('transferredtoReferredBy')
            ->addField('transferredtoSalutation')
            ->addField('transferredtoSendMail')
            ->addField('transferredtoState')
            ->addField('transferredtoTitle')
            ->addField('transferredtoPostalcode')
            ->addField('animalGroups')
            ->addField('animalExportAccounts')
            ->addField('animalPictures')
            ->addField('animalVideos')
            ->addField('animalVideoUrls')
            ->setCalculateFoundRows(true);

        $data = $this->api->getPostObject($query);

        $this->assertEquals('animals', $data['objectType']);
        $this->assertEquals('search', $data['objectAction']);
        $this->assertEquals(33, $data['search']->resultStart);
        $this->assertEquals(123, $data['search']->resultLimit);
        $this->assertEquals('testSortValue', $data['search']->resultSort);
        $this->assertEquals('ascending', $data['search']->resultOrder);
        $this->assertEquals('Yes', $data['search']->calcFoundRows);
        
        $translatedFields = [
            "animalID",
            "animalActivityLevel",
            "animalAdoptedDate",
            "animalAdoptionFee",
            "animalAdoptionLead",
            "animalAdoptionLeadID",
            "animalAltered",
            "animalApplicationID",
            "animalAvailableDate",
            "animalBirthdate",
            "animalBirthdateExact",
            "animalBreed",
            "animalCoatLength",
            "animalColonyID",
            "animalColor",
            "animalColorID",
            "animalColorDetails",
            "animalCondition",
            "animalConditionID",
            "animalCost",
            "animalCourtesy",
            "animalCreatedDate",
            "animalCreatedBy",
            "animalCreatedByID",
            "animalCreatedTimeframe",
            "animalDaysInFoster",
            "animalDeclawed",
            "animalDescription",
            "animalDescriptionPlain",
            "animalDistinguishingMarks",
            "animalAllowExport",
            "animalEarType",
            "animalEnergyLevel",
            "animalExerciseNeeds",
            "animalEyeColor",
            "animalFence",
            "animalFosterID",
            "animalFound",
            "animalFoundDate",
            "animalFoundPostalcode",
            "animalGeneralAge",
            "animalGeneralSizePotential",
            "animalGroomingNeeds",
            "animalHighlightOrder",
            "animalHousetrained",
            "animalIndoorOutdoor",
            "animalIntakes",
            "animalInternalID",
            "animalKillDate",
            "animalKillReason",
            "animalUpdatedBy",
            "animalUpdatedByID",
            "animalUpdatedDate",
            "animalUpdatedTimeframe",
            "animalLocationID",
            "animalLocationPublic",
            "animalMicrochipped",
            "animalMicrochipNumber",
            "animalMicrochipVendor",
            "animalMixedBreed",
            "animalName",
            "animalSpecialneeds",
            "animalSpecialneedsDescription",
            "animalNeedsFoster",
            "animalNewPeople",
            "animalNotes",
            "animalNotHousetrainedReason",
            "animalObedienceTraining",
            "animalOKWithAdults",
            "animalOKWithCats",
            "animalOKWithDogs",
            "animalOKWithKids",
            "animalOpenIntakes",
            "animalOrigin",
            "animalOthernames",
            "animalOutcomes",
            "animalOwnerExperience",
            "animalOwnerID",
            "animalPattern",
            "animalPatternID",
            "animalAdoptionPending",
            "animalPrimaryBreed",
            "animalPrimaryBreedID",
            "animalReceivedDate",
            "animalRescueID",
            "animalSecondaryBreed",
            "animalSecondaryBreedID",
            "animalSex",
            "animalShared",
            "animalShedding",
            "animalSizeCurrent",
            "animalSizePotential",
            "animalSizeUOM",
            "animalSpecies",
            "animalSpeciesID",
            "animalSponsorable",
            "animalSponsors",
            "animalSponsorshipDetails",
            "animalSponsorshipMinimum",
            "animalStatus",
            "animalStatusID",
            "animalSummary",
            "animalTailType",
            "animalTransferredToID",
            "animalUptodate",
            "animalVocal",
            "animalYardRequired",
            "animalAffectionate",
            "animalApartment",
            "animalCratetrained",
            "animalDrools",
            "animalEagerToPlease",
            "animalEscapes",
            "animalEventempered",
            "animalFetches",
            "animalGentle",
            "animalGoodInCar",
            "animalGoofy",
            "animalHasAllergies",
            "animalHearingImpaired",
            "animalHypoallergenic",
            "animalIndependent",
            "animalIntelligent",
            "animalLap",
            "animalLeashtrained",
            "animalNeedsCompanionAnimal",
            "animalNoCold",
            "animalNoFemaleDogs",
            "animalNoHeat",
            "animalNoLargeDogs",
            "animalNoMaleDogs",
            "animalNoSmallDogs",
            "animalObedient",
            "animalOKForSeniors",
            "animalOKWithFarmAnimals",
            "animalOlderKidsOnly",
            "animalOngoingMedical",
            "animalPlayful",
            "animalPlaysToys",
            "animalPredatory",
            "animalProtective",
            "animalSightImpaired",
            "animalSkittish",
            "animalSpecialDiet",
            "animalSwims",
            "animalTimid",
            "ownerID",
            "ownerActive",
            "ownerAddress",
            "ownerBounces",
            "ownerCarrier",
            "ownerCity",
            "ownerComment",
            "ownerCompany",
            "ownerCountry",
            "ownerCounty",
            "ownerEmail",
            "ownerEmailAlt",
            "ownerEmailPager",
            "ownerFax",
            "ownerFirstname",
            "ownerLastname",
            "ownerName",
            "ownerPhoneCell",
            "ownerPhoneHome",
            "ownerPhoneWork",
            "ownerPhoneWorkExt",
            "ownerPlus4",
            "ownerReferredBy",
            "ownerSalutation",
            "ownerSendMail",
            "ownerState",
            "ownerTitle",
            "ownerPostalcode",
            "colonyAnimals",
            "colonyCaretakers",
            "colonyLocation",
            "colonyLocationID",
            "colonyName",
            "colonyRegisteredDate",
            "colonySpecificLocation",
            "fosterID",
            "fosterActive",
            "fosterAddress",
            "fosterBounces",
            "fosterCarrier",
            "fosterCity",
            "fosterComment",
            "fosterCompany",
            "fosterCountry",
            "fosterCounty",
            "fosterEmail",
            "fosterEmailAlt",
            "fosterEmailPager",
            "fosterFax",
            "fosterFirstname",
            "fosterLastname",
            "fosterName",
            "fosterPhoneCell",
            "fosterPhoneHome",
            "fosterPhoneWork",
            "fosterPhoneWorkExt",
            "fosterPlus4",
            "fosterReferredBy",
            "fosterSalutation",
            "fosterSendMail",
            "fosterState",
            "fosterTitle",
            "fosterPostalcode",
            "locationAddress",
            "locationAnimals",
            "locationCity",
            "locationColonies",
            "locationCountry",
            "locationUrl",
            "locationEvents",
            "locationMeetrequests",
            "locationName",
            "locationPhone",
            "locationState",
            "locationPostalcode",
            "submittedformID",
            "submittedformAnimalID",
            "submittedformAssignedToID",
            "submittedformCommentsCount",
            "submittedformCommentsInline",
            "submittedformCompletedDate",
            "submittedformFormName",
            "submittedformPending",
            "submittedformStatus",
            "submittedformStepsCount",
            "submitterID",
            "submitterActive",
            "submitterAddress",
            "submitterBounces",
            "submitterCarrier",
            "submitterCity",
            "submitterComment",
            "submitterCompany",
            "submitterCountry",
            "submitterCounty",
            "submitterEmail",
            "submitterEmailAlt",
            "submitterEmailPager",
            "submitterFax",
            "submitterFirstname",
            "submitterLastname",
            "submitterName",
            "submitterPhoneCell",
            "submitterPhoneHome",
            "submitterPhoneWork",
            "submitterPhoneWorkExt",
            "submitterPlus4",
            "submitterReferredBy",
            "submitterSalutation",
            "submitterSendMail",
            "submitterState",
            "submitterTitle",
            "submitterPostalcode",
            "transferredtoActive",
            "transferredtoAddress",
            "transferredtoBounces",
            "transferredtoCarrier",
            "transferredtoCity",
            "transferredtoComment",
            "transferredtoCompany",
            "transferredtoID",
            "transferredtoCountry",
            "transferredtoCounty",
            "transferredtoEmail",
            "transferredtoEmailAlt",
            "transferredtoEmailPager",
            "transferredtoFax",
            "transferredtoFirstname",
            "transferredtoLastname",
            "transferredtoName",
            "transferredtoPhoneCell",
            "transferredtoPhoneHome",
            "transferredtoPhoneWork",
            "transferredtoPhoneWorkExt",
            "transferredtoPlus4",
            "transferredtoReferredBy",
            "transferredtoSalutation",
            "transferredtoSendMail",
            "transferredtoState",
            "transferredtoTitle",
            "transferredtoPostalcode",
            "animalGroups",
            "animalExportAccounts",
            "animalPictures",
            "animalVideos",
            "animalVideoUrls",
        ];

        $this->assertEquals($translatedFields, $data['search']->fields);
    }
}
