<?php
/**
 * Animals Search Request
 *
 * @package RescueGroups
 * @subpackage Request
 * @author SourceGenerator
 */
namespace RescueGroups\Request\Objects\Animals;

class Search extends \RescueGroups\Request\Objects\Base implements
    \RescueGroups\Request\ParametersInterface,
    \RescueGroups\Request\ProcessResponseInterface
{
    use \RescueGroups\Request\Traits\SearchParameters;

    /**
     * Query object type
     */
    const QUERY_OBJECT_TYPE = 'animals';

    /**
     * Query object action
     */
    const QUERY_OBJECT_ACTION = 'search';

    /**
     * Query login is required
     */
    const QUERY_LOGIN_REQUIRED = true;

    const FIELD_ID = 'id';
    const FIELD_ACTIVITY_LEVEL = 'activityLevel';
    const FIELD_ADOPTED_DATE = 'adoptedDate';
    const FIELD_ADOPTION_FEE = 'adoptionFee';
    const FIELD_ADOPTION_LEAD = 'adoptionLead';
    const FIELD_ADOPTION_LEAD_ID = 'adoptionLeadId';
    const FIELD_ALTERED = 'altered';
    const FIELD_APPLICATION_ID = 'applicationId';
    const FIELD_AVAILABLE_DATE = 'availableDate';
    const FIELD_BIRTHDATE = 'birthdate';
    const FIELD_BIRTHDATE_EXACT = 'birthdateExact';
    const FIELD_BREED = 'breed';
    const FIELD_COAT_LENGTH = 'coatLength';
    const FIELD_COLONY_ID = 'colonyId';
    const FIELD_COLOR = 'color';
    const FIELD_COLOR_ID = 'colorId';
    const FIELD_COLOR_DETAILS = 'colorDetails';
    const FIELD_CONDITION = 'condition';
    const FIELD_CONDITION_ID = 'conditionId';
    const FIELD_COST = 'cost';
    const FIELD_COURTESY = 'courtesy';
    const FIELD_CREATED_DATE = 'createdDate';
    const FIELD_CREATED_BY = 'createdBy';
    const FIELD_CREATED_BY_ID = 'createdById';
    const FIELD_CREATED_TIMEFRAME = 'createdTimeframe';
    const FIELD_DAYS_IN_FOSTER = 'daysInFoster';
    const FIELD_DECLAWED = 'declawed';
    const FIELD_DESCRIPTION = 'description';
    const FIELD_DESCRIPTION_PLAIN = 'descriptionPlain';
    const FIELD_DISTINGUISHING_MARKS = 'distinguishingMarks';
    const FIELD_ALLOW_EXPORT = 'allowExport';
    const FIELD_EAR_TYPE = 'earType';
    const FIELD_ENERGY_LEVEL = 'energyLevel';
    const FIELD_EXERCISE_NEEDS = 'exerciseNeeds';
    const FIELD_EYE_COLOR = 'eyeColor';
    const FIELD_FENCE = 'fence';
    const FIELD_FOSTER_ID = 'fosterId';
    const FIELD_FOUND = 'found';
    const FIELD_FOUND_DATE = 'foundDate';
    const FIELD_FOUND_POSTALCODE = 'foundPostalcode';
    const FIELD_GENERAL_AGE = 'generalAge';
    const FIELD_GENERAL_SIZE_POTENTIAL = 'generalSizePotential';
    const FIELD_GROOMING_NEEDS = 'groomingNeeds';
    const FIELD_HIGHLIGHT_ORDER = 'highlightOrder';
    const FIELD_HOUSETRAINED = 'housetrained';
    const FIELD_INDOOR_OUTDOOR = 'indoorOutdoor';
    const FIELD_INTAKES = 'intakes';
    const FIELD_INTERNAL_ID = 'internalId';
    const FIELD_KILL_DATE = 'killDate';
    const FIELD_KILL_REASON = 'killReason';
    const FIELD_UPDATED_BY = 'updatedBy';
    const FIELD_UPDATED_BY_ID = 'updatedById';
    const FIELD_UPDATED_DATE = 'updatedDate';
    const FIELD_UPDATED_TIMEFRAME = 'updatedTimeframe';
    const FIELD_LOCATION_ID = 'locationId';
    const FIELD_LOCATION_PUBLIC = 'locationPublic';
    const FIELD_MICROCHIPPED = 'microchipped';
    const FIELD_MICROCHIP_NUMBER = 'microchipNumber';
    const FIELD_MICROCHIP_VENDOR = 'microchipVendor';
    const FIELD_MIXED_BREED = 'mixedBreed';
    const FIELD_NAME = 'name';
    const FIELD_SPECIALNEEDS = 'specialneeds';
    const FIELD_SPECIALNEEDS_DESCRIPTION = 'specialneedsDescription';
    const FIELD_NEEDS_FOSTER = 'needsFoster';
    const FIELD_NEW_PEOPLE = 'newPeople';
    const FIELD_NOTES = 'notes';
    const FIELD_NOT_HOUSETRAINED_REASON = 'notHousetrainedReason';
    const FIELD_OBEDIENCE_TRAINING = 'obedienceTraining';
    const FIELD_OK_WITH_ADULTS = 'okWithAdults';
    const FIELD_OK_WITH_CATS = 'okWithCats';
    const FIELD_OK_WITH_DOGS = 'okWithDogs';
    const FIELD_OK_WITH_KIDS = 'okWithKids';
    const FIELD_OPEN_INTAKES = 'openIntakes';
    const FIELD_ORIGIN = 'origin';
    const FIELD_OTHERNAMES = 'othernames';
    const FIELD_OUTCOMES = 'outcomes';
    const FIELD_OWNER_EXPERIENCE = 'ownerExperience';
    const FIELD_OWNER_ID = 'ownerId';
    const FIELD_PATTERN = 'pattern';
    const FIELD_PATTERN_ID = 'patternId';
    const FIELD_ADOPTION_PENDING = 'adoptionPending';
    const FIELD_PRIMARY_BREED = 'primaryBreed';
    const FIELD_PRIMARY_BREED_ID = 'primaryBreedId';
    const FIELD_RECEIVED_DATE = 'receivedDate';
    const FIELD_RESCUE_ID = 'rescueId';
    const FIELD_SECONDARY_BREED = 'secondaryBreed';
    const FIELD_SECONDARY_BREED_ID = 'secondaryBreedId';
    const FIELD_SEX = 'sex';
    const FIELD_SHARED = 'shared';
    const FIELD_SHEDDING = 'shedding';
    const FIELD_SIZE_CURRENT = 'sizeCurrent';
    const FIELD_SIZE_POTENTIAL = 'sizePotential';
    const FIELD_SIZE_U_O_M = 'sizeUOM';
    const FIELD_SPECIES = 'species';
    const FIELD_SPECIES_ID = 'speciesId';
    const FIELD_SPONSORABLE = 'sponsorable';
    const FIELD_SPONSORS = 'sponsors';
    const FIELD_SPONSORSHIP_DETAILS = 'sponsorshipDetails';
    const FIELD_SPONSORSHIP_MINIMUM = 'sponsorshipMinimum';
    const FIELD_STATUS = 'status';
    const FIELD_STATUS_ID = 'statusId';
    const FIELD_SUMMARY = 'summary';
    const FIELD_TAIL_TYPE = 'tailType';
    const FIELD_TRANSFERRED_TO_ID = 'transferredToId';
    const FIELD_UPTODATE = 'uptodate';
    const FIELD_VOCAL = 'vocal';
    const FIELD_YARD_REQUIRED = 'yardRequired';
    const FIELD_AFFECTIONATE = 'affectionate';
    const FIELD_APARTMENT = 'apartment';
    const FIELD_CRATETRAINED = 'cratetrained';
    const FIELD_DROOLS = 'drools';
    const FIELD_EAGER_TO_PLEASE = 'eagerToPlease';
    const FIELD_ESCAPES = 'escapes';
    const FIELD_EVENTEMPERED = 'eventempered';
    const FIELD_FETCHES = 'fetches';
    const FIELD_GENTLE = 'gentle';
    const FIELD_GOOD_IN_CAR = 'goodInCar';
    const FIELD_GOOFY = 'goofy';
    const FIELD_HAS_ALLERGIES = 'hasAllergies';
    const FIELD_HEARING_IMPAIRED = 'hearingImpaired';
    const FIELD_HYPOALLERGENIC = 'hypoallergenic';
    const FIELD_INDEPENDENT = 'independent';
    const FIELD_INTELLIGENT = 'intelligent';
    const FIELD_LAP = 'lap';
    const FIELD_LEASHTRAINED = 'leashtrained';
    const FIELD_NEEDS_COMPANION = 'needsCompanion';
    const FIELD_NO_COLD = 'noCold';
    const FIELD_NO_FEMALE_DOGS = 'noFemaleDogs';
    const FIELD_NO_HEAT = 'noHeat';
    const FIELD_NO_LARGE_DOGS = 'noLargeDogs';
    const FIELD_NO_MALE_DOGS = 'noMaleDogs';
    const FIELD_NO_SMALL_DOGS = 'noSmallDogs';
    const FIELD_OBEDIENT = 'obedient';
    const FIELD_OK_FOR_SENIORS = 'okForSeniors';
    const FIELD_OK_WITH_FARMS = 'okWithFarms';
    const FIELD_OLDER_KIDS_ONLY = 'olderKidsOnly';
    const FIELD_ONGOING_MEDICAL = 'ongoingMedical';
    const FIELD_PLAYFUL = 'playful';
    const FIELD_PLAYS_TOYS = 'playsToys';
    const FIELD_PREDATORY = 'predatory';
    const FIELD_PROTECTIVE = 'protective';
    const FIELD_SIGHT_IMPAIRED = 'sightImpaired';
    const FIELD_SKITTISH = 'skittish';
    const FIELD_SPECIAL_DIET = 'specialDiet';
    const FIELD_SWIMS = 'swims';
    const FIELD_TIMID = 'timid';
    const FIELD_OWNER_ACTIVE = 'ownerActive';
    const FIELD_OWNER_ADDRESS = 'ownerAddress';
    const FIELD_OWNER_BOUNCES = 'ownerBounces';
    const FIELD_OWNER_CARRIER = 'ownerCarrier';
    const FIELD_OWNER_CITY = 'ownerCity';
    const FIELD_OWNER_COMMENT = 'ownerComment';
    const FIELD_OWNER_COMPANY = 'ownerCompany';
    const FIELD_OWNER_COUNTRY = 'ownerCountry';
    const FIELD_OWNER_COUNTY = 'ownerCounty';
    const FIELD_OWNER_EMAIL = 'ownerEmail';
    const FIELD_OWNER_EMAIL_ALT = 'ownerEmailAlt';
    const FIELD_OWNER_EMAIL_PAGER = 'ownerEmailPager';
    const FIELD_OWNER_FAX = 'ownerFax';
    const FIELD_OWNER_FIRSTNAME = 'ownerFirstname';
    const FIELD_OWNER_LASTNAME = 'ownerLastname';
    const FIELD_OWNER_NAME = 'ownerName';
    const FIELD_OWNER_PHONE_CELL = 'ownerPhoneCell';
    const FIELD_OWNER_PHONE_HOME = 'ownerPhoneHome';
    const FIELD_OWNER_PHONE_WORK = 'ownerPhoneWork';
    const FIELD_OWNER_PHONE_WORK_EXT = 'ownerPhoneWorkExt';
    const FIELD_OWNER_PLUS4 = 'ownerPlus4';
    const FIELD_OWNER_REFERRED_BY = 'ownerReferredBy';
    const FIELD_OWNER_SALUTATION = 'ownerSalutation';
    const FIELD_OWNER_SEND_MAIL = 'ownerSendMail';
    const FIELD_OWNER_STATE = 'ownerState';
    const FIELD_OWNER_TITLE = 'ownerTitle';
    const FIELD_OWNER_POSTALCODE = 'ownerPostalcode';
    const FIELD_COLONYS = 'colonys';
    const FIELD_COLONY_CARETAKERS = 'colonyCaretakers';
    const FIELD_COLONY_LOCATION = 'colonyLocation';
    const FIELD_COLONY_LOCATION_ID = 'colonyLocationId';
    const FIELD_COLONY_NAME = 'colonyName';
    const FIELD_COLONY_REGISTERED_DATE = 'colonyRegisteredDate';
    const FIELD_COLONY_SPECIFIC_LOCATION = 'colonySpecificLocation';
    const FIELD_FOSTER_ACTIVE = 'fosterActive';
    const FIELD_FOSTER_ADDRESS = 'fosterAddress';
    const FIELD_FOSTER_BOUNCES = 'fosterBounces';
    const FIELD_FOSTER_CARRIER = 'fosterCarrier';
    const FIELD_FOSTER_CITY = 'fosterCity';
    const FIELD_FOSTER_COMMENT = 'fosterComment';
    const FIELD_FOSTER_COMPANY = 'fosterCompany';
    const FIELD_FOSTER_COUNTRY = 'fosterCountry';
    const FIELD_FOSTER_COUNTY = 'fosterCounty';
    const FIELD_FOSTER_EMAIL = 'fosterEmail';
    const FIELD_FOSTER_EMAIL_ALT = 'fosterEmailAlt';
    const FIELD_FOSTER_EMAIL_PAGER = 'fosterEmailPager';
    const FIELD_FOSTER_FAX = 'fosterFax';
    const FIELD_FOSTER_FIRSTNAME = 'fosterFirstname';
    const FIELD_FOSTER_LASTNAME = 'fosterLastname';
    const FIELD_FOSTER_NAME = 'fosterName';
    const FIELD_FOSTER_PHONE_CELL = 'fosterPhoneCell';
    const FIELD_FOSTER_PHONE_HOME = 'fosterPhoneHome';
    const FIELD_FOSTER_PHONE_WORK = 'fosterPhoneWork';
    const FIELD_FOSTER_PHONE_WORK_EXT = 'fosterPhoneWorkExt';
    const FIELD_FOSTER_PLUS4 = 'fosterPlus4';
    const FIELD_FOSTER_REFERRED_BY = 'fosterReferredBy';
    const FIELD_FOSTER_SALUTATION = 'fosterSalutation';
    const FIELD_FOSTER_SEND_MAIL = 'fosterSendMail';
    const FIELD_FOSTER_STATE = 'fosterState';
    const FIELD_FOSTER_TITLE = 'fosterTitle';
    const FIELD_FOSTER_POSTALCODE = 'fosterPostalcode';
    const FIELD_LOCATION_ADDRESS = 'locationAddress';
    const FIELD_LOCATIONS = 'locations';
    const FIELD_LOCATION_CITY = 'locationCity';
    const FIELD_LOCATION_COLONIES = 'locationColonies';
    const FIELD_LOCATION_COUNTRY = 'locationCountry';
    const FIELD_LOCATION_URL = 'locationUrl';
    const FIELD_LOCATION_EVENTS = 'locationEvents';
    const FIELD_LOCATION_MEETREQUESTS = 'locationMeetrequests';
    const FIELD_LOCATION_NAME = 'locationName';
    const FIELD_LOCATION_PHONE = 'locationPhone';
    const FIELD_LOCATION_STATE = 'locationState';
    const FIELD_LOCATION_POSTALCODE = 'locationPostalcode';
    const FIELD_SUBMITTEDFORM_ID = 'submittedformId';
    const FIELD_SUBMITTEDFORM_ASSIGNED_TO_ID = 'submittedformAssignedToId';
    const FIELD_SUBMITTEDFORM_COMMENTS_COUNT = 'submittedformCommentsCount';
    const FIELD_SUBMITTEDFORM_COMMENTS_INLINE = 'submittedformCommentsInline';
    const FIELD_SUBMITTEDFORM_COMPLETED_DATE = 'submittedformCompletedDate';
    const FIELD_SUBMITTEDFORM_FORM_NAME = 'submittedformFormName';
    const FIELD_SUBMITTEDFORM_PENDING = 'submittedformPending';
    const FIELD_SUBMITTEDFORM_STATUS = 'submittedformStatus';
    const FIELD_SUBMITTEDFORM_STEPS_COUNT = 'submittedformStepsCount';
    const FIELD_SUBMITTER_ID = 'submitterId';
    const FIELD_SUBMITTER_ACTIVE = 'submitterActive';
    const FIELD_SUBMITTER_ADDRESS = 'submitterAddress';
    const FIELD_SUBMITTER_BOUNCES = 'submitterBounces';
    const FIELD_SUBMITTER_CARRIER = 'submitterCarrier';
    const FIELD_SUBMITTER_CITY = 'submitterCity';
    const FIELD_SUBMITTER_COMMENT = 'submitterComment';
    const FIELD_SUBMITTER_COMPANY = 'submitterCompany';
    const FIELD_SUBMITTER_COUNTRY = 'submitterCountry';
    const FIELD_SUBMITTER_COUNTY = 'submitterCounty';
    const FIELD_SUBMITTER_EMAIL = 'submitterEmail';
    const FIELD_SUBMITTER_EMAIL_ALT = 'submitterEmailAlt';
    const FIELD_SUBMITTER_EMAIL_PAGER = 'submitterEmailPager';
    const FIELD_SUBMITTER_FAX = 'submitterFax';
    const FIELD_SUBMITTER_FIRSTNAME = 'submitterFirstname';
    const FIELD_SUBMITTER_LASTNAME = 'submitterLastname';
    const FIELD_SUBMITTER_NAME = 'submitterName';
    const FIELD_SUBMITTER_PHONE_CELL = 'submitterPhoneCell';
    const FIELD_SUBMITTER_PHONE_HOME = 'submitterPhoneHome';
    const FIELD_SUBMITTER_PHONE_WORK = 'submitterPhoneWork';
    const FIELD_SUBMITTER_PHONE_WORK_EXT = 'submitterPhoneWorkExt';
    const FIELD_SUBMITTER_PLUS4 = 'submitterPlus4';
    const FIELD_SUBMITTER_REFERRED_BY = 'submitterReferredBy';
    const FIELD_SUBMITTER_SALUTATION = 'submitterSalutation';
    const FIELD_SUBMITTER_SEND_MAIL = 'submitterSendMail';
    const FIELD_SUBMITTER_STATE = 'submitterState';
    const FIELD_SUBMITTER_TITLE = 'submitterTitle';
    const FIELD_SUBMITTER_POSTALCODE = 'submitterPostalcode';
    const FIELD_TRANSFERREDTO_ACTIVE = 'transferredtoActive';
    const FIELD_TRANSFERREDTO_ADDRESS = 'transferredtoAddress';
    const FIELD_TRANSFERREDTO_BOUNCES = 'transferredtoBounces';
    const FIELD_TRANSFERREDTO_CARRIER = 'transferredtoCarrier';
    const FIELD_TRANSFERREDTO_CITY = 'transferredtoCity';
    const FIELD_TRANSFERREDTO_COMMENT = 'transferredtoComment';
    const FIELD_TRANSFERREDTO_COMPANY = 'transferredtoCompany';
    const FIELD_TRANSFERREDTO_ID = 'transferredtoId';
    const FIELD_TRANSFERREDTO_COUNTRY = 'transferredtoCountry';
    const FIELD_TRANSFERREDTO_COUNTY = 'transferredtoCounty';
    const FIELD_TRANSFERREDTO_EMAIL = 'transferredtoEmail';
    const FIELD_TRANSFERREDTO_EMAIL_ALT = 'transferredtoEmailAlt';
    const FIELD_TRANSFERREDTO_EMAIL_PAGER = 'transferredtoEmailPager';
    const FIELD_TRANSFERREDTO_FAX = 'transferredtoFax';
    const FIELD_TRANSFERREDTO_FIRSTNAME = 'transferredtoFirstname';
    const FIELD_TRANSFERREDTO_LASTNAME = 'transferredtoLastname';
    const FIELD_TRANSFERREDTO_NAME = 'transferredtoName';
    const FIELD_TRANSFERREDTO_PHONE_CELL = 'transferredtoPhoneCell';
    const FIELD_TRANSFERREDTO_PHONE_HOME = 'transferredtoPhoneHome';
    const FIELD_TRANSFERREDTO_PHONE_WORK = 'transferredtoPhoneWork';
    const FIELD_TRANSFERREDTO_PHONE_WORK_EXT = 'transferredtoPhoneWorkExt';
    const FIELD_TRANSFERREDTO_PLUS4 = 'transferredtoPlus4';
    const FIELD_TRANSFERREDTO_REFERRED_BY = 'transferredtoReferredBy';
    const FIELD_TRANSFERREDTO_SALUTATION = 'transferredtoSalutation';
    const FIELD_TRANSFERREDTO_SEND_MAIL = 'transferredtoSendMail';
    const FIELD_TRANSFERREDTO_STATE = 'transferredtoState';
    const FIELD_TRANSFERREDTO_TITLE = 'transferredtoTitle';
    const FIELD_TRANSFERREDTO_POSTALCODE = 'transferredtoPostalcode';
    const FIELD_GROUPS = 'groups';
    const FIELD_EXPORT_ACCOUNTS = 'exportAccounts';
    const FIELD_PICTURES = 'pictures';
    const FIELD_VIDEOS = 'videos';
    const FIELD_VIDEO_URLS = 'videoUrls';

    /**
     * Filterable Fields
     *
     * @var array
     */
    private $objectFields = [
        "id" => [1, 'animalID'],
        "activityLevel" => [0, 'animalActivityLevel'],
        "adoptedDate" => [0, 'animalAdoptedDate'],
        "adoptionFee" => [0, 'animalAdoptionFee'],
        "adoptionLead" => [0, 'animalAdoptionLead'],
        "adoptionLeadId" => [0, 'animalAdoptionLeadID'],
        "altered" => [0, 'animalAltered'],
        "applicationId" => [0, 'animalApplicationID'],
        "availableDate" => [0, 'animalAvailableDate'],
        "birthdate" => [0, 'animalBirthdate'],
        "birthdateExact" => [0, 'animalBirthdateExact'],
        "breed" => [0, 'animalBreed'],
        "coatLength" => [0, 'animalCoatLength'],
        "colonyId" => [0, 'animalColonyID'],
        "color" => [0, 'animalColor'],
        "colorId" => [0, 'animalColorID'],
        "colorDetails" => [0, 'animalColorDetails'],
        "condition" => [0, 'animalCondition'],
        "conditionId" => [0, 'animalConditionID'],
        "cost" => [0, 'animalCost'],
        "courtesy" => [0, 'animalCourtesy'],
        "createdDate" => [0, 'animalCreatedDate'],
        "createdBy" => [0, 'animalCreatedBy'],
        "createdById" => [0, 'animalCreatedByID'],
        "createdTimeframe" => [0, 'animalCreatedTimeframe'],
        "daysInFoster" => [0, 'animalDaysInFoster'],
        "declawed" => [0, 'animalDeclawed'],
        "description" => [0, 'animalDescription'],
        "descriptionPlain" => [0, 'animalDescriptionPlain'],
        "distinguishingMarks" => [0, 'animalDistinguishingMarks'],
        "allowExport" => [0, 'animalAllowExport'],
        "earType" => [0, 'animalEarType'],
        "energyLevel" => [0, 'animalEnergyLevel'],
        "exerciseNeeds" => [0, 'animalExerciseNeeds'],
        "eyeColor" => [0, 'animalEyeColor'],
        "fence" => [0, 'animalFence'],
        "fosterId" => [0, 'animalFosterID'],
        "found" => [0, 'animalFound'],
        "foundDate" => [0, 'animalFoundDate'],
        "foundPostalcode" => [0, 'animalFoundPostalcode'],
        "generalAge" => [0, 'animalGeneralAge'],
        "generalSizePotential" => [0, 'animalGeneralSizePotential'],
        "groomingNeeds" => [0, 'animalGroomingNeeds'],
        "highlightOrder" => [0, 'animalHighlightOrder'],
        "housetrained" => [0, 'animalHousetrained'],
        "indoorOutdoor" => [0, 'animalIndoorOutdoor'],
        "intakes" => [0, 'animalIntakes'],
        "internalId" => [0, 'animalInternalID'],
        "killDate" => [0, 'animalKillDate'],
        "killReason" => [0, 'animalKillReason'],
        "updatedBy" => [0, 'animalUpdatedBy'],
        "updatedById" => [0, 'animalUpdatedByID'],
        "updatedDate" => [0, 'animalUpdatedDate'],
        "updatedTimeframe" => [0, 'animalUpdatedTimeframe'],
        "locationId" => [0, 'animalLocationID'],
        "locationPublic" => [0, 'animalLocationPublic'],
        "microchipped" => [0, 'animalMicrochipped'],
        "microchipNumber" => [0, 'animalMicrochipNumber'],
        "microchipVendor" => [0, 'animalMicrochipVendor'],
        "mixedBreed" => [0, 'animalMixedBreed'],
        "name" => [0, 'animalName'],
        "specialneeds" => [0, 'animalSpecialneeds'],
        "specialneedsDescription" => [0, 'animalSpecialneedsDescription'],
        "needsFoster" => [0, 'animalNeedsFoster'],
        "newPeople" => [0, 'animalNewPeople'],
        "notes" => [0, 'animalNotes'],
        "notHousetrainedReason" => [0, 'animalNotHousetrainedReason'],
        "obedienceTraining" => [0, 'animalObedienceTraining'],
        "okWithAdults" => [0, 'animalOKWithAdults'],
        "okWithCats" => [0, 'animalOKWithCats'],
        "okWithDogs" => [0, 'animalOKWithDogs'],
        "okWithKids" => [0, 'animalOKWithKids'],
        "openIntakes" => [0, 'animalOpenIntakes'],
        "origin" => [0, 'animalOrigin'],
        "othernames" => [0, 'animalOthernames'],
        "outcomes" => [0, 'animalOutcomes'],
        "ownerExperience" => [0, 'animalOwnerExperience'],
        "ownerId" => [0, 'animalOwnerID'],
        "pattern" => [0, 'animalPattern'],
        "patternId" => [0, 'animalPatternID'],
        "adoptionPending" => [0, 'animalAdoptionPending'],
        "primaryBreed" => [0, 'animalPrimaryBreed'],
        "primaryBreedId" => [0, 'animalPrimaryBreedID'],
        "receivedDate" => [0, 'animalReceivedDate'],
        "rescueId" => [0, 'animalRescueID'],
        "secondaryBreed" => [0, 'animalSecondaryBreed'],
        "secondaryBreedId" => [0, 'animalSecondaryBreedID'],
        "sex" => [0, 'animalSex'],
        "shared" => [0, 'animalShared'],
        "shedding" => [0, 'animalShedding'],
        "sizeCurrent" => [0, 'animalSizeCurrent'],
        "sizePotential" => [0, 'animalSizePotential'],
        "sizeUOM" => [0, 'animalSizeUOM'],
        "species" => [0, 'animalSpecies'],
        "speciesId" => [0, 'animalSpeciesID'],
        "sponsorable" => [0, 'animalSponsorable'],
        "sponsors" => [0, 'animalSponsors'],
        "sponsorshipDetails" => [0, 'animalSponsorshipDetails'],
        "sponsorshipMinimum" => [0, 'animalSponsorshipMinimum'],
        "status" => [0, 'animalStatus'],
        "statusId" => [0, 'animalStatusID'],
        "summary" => [0, 'animalSummary'],
        "tailType" => [0, 'animalTailType'],
        "transferredToId" => [0, 'animalTransferredToID'],
        "uptodate" => [0, 'animalUptodate'],
        "vocal" => [0, 'animalVocal'],
        "yardRequired" => [0, 'animalYardRequired'],
        "affectionate" => [0, 'animalAffectionate'],
        "apartment" => [0, 'animalApartment'],
        "cratetrained" => [0, 'animalCratetrained'],
        "drools" => [0, 'animalDrools'],
        "eagerToPlease" => [0, 'animalEagerToPlease'],
        "escapes" => [0, 'animalEscapes'],
        "eventempered" => [0, 'animalEventempered'],
        "fetches" => [0, 'animalFetches'],
        "gentle" => [0, 'animalGentle'],
        "goodInCar" => [0, 'animalGoodInCar'],
        "goofy" => [0, 'animalGoofy'],
        "hasAllergies" => [0, 'animalHasAllergies'],
        "hearingImpaired" => [0, 'animalHearingImpaired'],
        "hypoallergenic" => [0, 'animalHypoallergenic'],
        "independent" => [0, 'animalIndependent'],
        "intelligent" => [0, 'animalIntelligent'],
        "lap" => [0, 'animalLap'],
        "leashtrained" => [0, 'animalLeashtrained'],
        "needsCompanion" => [0, 'animalNeedsCompanionAnimal'],
        "noCold" => [0, 'animalNoCold'],
        "noFemaleDogs" => [0, 'animalNoFemaleDogs'],
        "noHeat" => [0, 'animalNoHeat'],
        "noLargeDogs" => [0, 'animalNoLargeDogs'],
        "noMaleDogs" => [0, 'animalNoMaleDogs'],
        "noSmallDogs" => [0, 'animalNoSmallDogs'],
        "obedient" => [0, 'animalObedient'],
        "okForSeniors" => [0, 'animalOKForSeniors'],
        "okWithFarms" => [0, 'animalOKWithFarmAnimals'],
        "olderKidsOnly" => [0, 'animalOlderKidsOnly'],
        "ongoingMedical" => [0, 'animalOngoingMedical'],
        "playful" => [0, 'animalPlayful'],
        "playsToys" => [0, 'animalPlaysToys'],
        "predatory" => [0, 'animalPredatory'],
        "protective" => [0, 'animalProtective'],
        "sightImpaired" => [0, 'animalSightImpaired'],
        "skittish" => [0, 'animalSkittish'],
        "specialDiet" => [0, 'animalSpecialDiet'],
        "swims" => [0, 'animalSwims'],
        "timid" => [0, 'animalTimid'],
        "ownerActive" => [0, 'ownerActive'],
        "ownerAddress" => [0, 'ownerAddress'],
        "ownerBounces" => [0, 'ownerBounces'],
        "ownerCarrier" => [0, 'ownerCarrier'],
        "ownerCity" => [0, 'ownerCity'],
        "ownerComment" => [0, 'ownerComment'],
        "ownerCompany" => [0, 'ownerCompany'],
        "ownerCountry" => [0, 'ownerCountry'],
        "ownerCounty" => [0, 'ownerCounty'],
        "ownerEmail" => [0, 'ownerEmail'],
        "ownerEmailAlt" => [0, 'ownerEmailAlt'],
        "ownerEmailPager" => [0, 'ownerEmailPager'],
        "ownerFax" => [0, 'ownerFax'],
        "ownerFirstname" => [0, 'ownerFirstname'],
        "ownerLastname" => [0, 'ownerLastname'],
        "ownerName" => [0, 'ownerName'],
        "ownerPhoneCell" => [0, 'ownerPhoneCell'],
        "ownerPhoneHome" => [0, 'ownerPhoneHome'],
        "ownerPhoneWork" => [0, 'ownerPhoneWork'],
        "ownerPhoneWorkExt" => [0, 'ownerPhoneWorkExt'],
        "ownerPlus4" => [0, 'ownerPlus4'],
        "ownerReferredBy" => [0, 'ownerReferredBy'],
        "ownerSalutation" => [0, 'ownerSalutation'],
        "ownerSendMail" => [0, 'ownerSendMail'],
        "ownerState" => [0, 'ownerState'],
        "ownerTitle" => [0, 'ownerTitle'],
        "ownerPostalcode" => [0, 'ownerPostalcode'],
        "colonys" => [0, 'colonyAnimals'],
        "colonyCaretakers" => [0, 'colonyCaretakers'],
        "colonyLocation" => [0, 'colonyLocation'],
        "colonyLocationId" => [0, 'colonyLocationID'],
        "colonyName" => [0, 'colonyName'],
        "colonyRegisteredDate" => [0, 'colonyRegisteredDate'],
        "colonySpecificLocation" => [0, 'colonySpecificLocation'],
        "fosterActive" => [0, 'fosterActive'],
        "fosterAddress" => [0, 'fosterAddress'],
        "fosterBounces" => [0, 'fosterBounces'],
        "fosterCarrier" => [0, 'fosterCarrier'],
        "fosterCity" => [0, 'fosterCity'],
        "fosterComment" => [0, 'fosterComment'],
        "fosterCompany" => [0, 'fosterCompany'],
        "fosterCountry" => [0, 'fosterCountry'],
        "fosterCounty" => [0, 'fosterCounty'],
        "fosterEmail" => [0, 'fosterEmail'],
        "fosterEmailAlt" => [0, 'fosterEmailAlt'],
        "fosterEmailPager" => [0, 'fosterEmailPager'],
        "fosterFax" => [0, 'fosterFax'],
        "fosterFirstname" => [0, 'fosterFirstname'],
        "fosterLastname" => [0, 'fosterLastname'],
        "fosterName" => [0, 'fosterName'],
        "fosterPhoneCell" => [0, 'fosterPhoneCell'],
        "fosterPhoneHome" => [0, 'fosterPhoneHome'],
        "fosterPhoneWork" => [0, 'fosterPhoneWork'],
        "fosterPhoneWorkExt" => [0, 'fosterPhoneWorkExt'],
        "fosterPlus4" => [0, 'fosterPlus4'],
        "fosterReferredBy" => [0, 'fosterReferredBy'],
        "fosterSalutation" => [0, 'fosterSalutation'],
        "fosterSendMail" => [0, 'fosterSendMail'],
        "fosterState" => [0, 'fosterState'],
        "fosterTitle" => [0, 'fosterTitle'],
        "fosterPostalcode" => [0, 'fosterPostalcode'],
        "locationAddress" => [0, 'locationAddress'],
        "locations" => [0, 'locationAnimals'],
        "locationCity" => [0, 'locationCity'],
        "locationColonies" => [0, 'locationColonies'],
        "locationCountry" => [0, 'locationCountry'],
        "locationUrl" => [0, 'locationUrl'],
        "locationEvents" => [0, 'locationEvents'],
        "locationMeetrequests" => [0, 'locationMeetrequests'],
        "locationName" => [0, 'locationName'],
        "locationPhone" => [0, 'locationPhone'],
        "locationState" => [0, 'locationState'],
        "locationPostalcode" => [0, 'locationPostalcode'],
        "submittedformId" => [0, 'submittedformID'],
        "submittedformAssignedToId" => [0, 'submittedformAssignedToID'],
        "submittedformCommentsCount" => [0, 'submittedformCommentsCount'],
        "submittedformCommentsInline" => [0, 'submittedformCommentsInline'],
        "submittedformCompletedDate" => [0, 'submittedformCompletedDate'],
        "submittedformFormName" => [0, 'submittedformFormName'],
        "submittedformPending" => [0, 'submittedformPending'],
        "submittedformStatus" => [0, 'submittedformStatus'],
        "submittedformStepsCount" => [0, 'submittedformStepsCount'],
        "submitterId" => [0, 'submitterID'],
        "submitterActive" => [0, 'submitterActive'],
        "submitterAddress" => [0, 'submitterAddress'],
        "submitterBounces" => [0, 'submitterBounces'],
        "submitterCarrier" => [0, 'submitterCarrier'],
        "submitterCity" => [0, 'submitterCity'],
        "submitterComment" => [0, 'submitterComment'],
        "submitterCompany" => [0, 'submitterCompany'],
        "submitterCountry" => [0, 'submitterCountry'],
        "submitterCounty" => [0, 'submitterCounty'],
        "submitterEmail" => [0, 'submitterEmail'],
        "submitterEmailAlt" => [0, 'submitterEmailAlt'],
        "submitterEmailPager" => [0, 'submitterEmailPager'],
        "submitterFax" => [0, 'submitterFax'],
        "submitterFirstname" => [0, 'submitterFirstname'],
        "submitterLastname" => [0, 'submitterLastname'],
        "submitterName" => [0, 'submitterName'],
        "submitterPhoneCell" => [0, 'submitterPhoneCell'],
        "submitterPhoneHome" => [0, 'submitterPhoneHome'],
        "submitterPhoneWork" => [0, 'submitterPhoneWork'],
        "submitterPhoneWorkExt" => [0, 'submitterPhoneWorkExt'],
        "submitterPlus4" => [0, 'submitterPlus4'],
        "submitterReferredBy" => [0, 'submitterReferredBy'],
        "submitterSalutation" => [0, 'submitterSalutation'],
        "submitterSendMail" => [0, 'submitterSendMail'],
        "submitterState" => [0, 'submitterState'],
        "submitterTitle" => [0, 'submitterTitle'],
        "submitterPostalcode" => [0, 'submitterPostalcode'],
        "transferredtoActive" => [0, 'transferredtoActive'],
        "transferredtoAddress" => [0, 'transferredtoAddress'],
        "transferredtoBounces" => [0, 'transferredtoBounces'],
        "transferredtoCarrier" => [0, 'transferredtoCarrier'],
        "transferredtoCity" => [0, 'transferredtoCity'],
        "transferredtoComment" => [0, 'transferredtoComment'],
        "transferredtoCompany" => [0, 'transferredtoCompany'],
        "transferredtoId" => [0, 'transferredtoID'],
        "transferredtoCountry" => [0, 'transferredtoCountry'],
        "transferredtoCounty" => [0, 'transferredtoCounty'],
        "transferredtoEmail" => [0, 'transferredtoEmail'],
        "transferredtoEmailAlt" => [0, 'transferredtoEmailAlt'],
        "transferredtoEmailPager" => [0, 'transferredtoEmailPager'],
        "transferredtoFax" => [0, 'transferredtoFax'],
        "transferredtoFirstname" => [0, 'transferredtoFirstname'],
        "transferredtoLastname" => [0, 'transferredtoLastname'],
        "transferredtoName" => [0, 'transferredtoName'],
        "transferredtoPhoneCell" => [0, 'transferredtoPhoneCell'],
        "transferredtoPhoneHome" => [0, 'transferredtoPhoneHome'],
        "transferredtoPhoneWork" => [0, 'transferredtoPhoneWork'],
        "transferredtoPhoneWorkExt" => [0, 'transferredtoPhoneWorkExt'],
        "transferredtoPlus4" => [0, 'transferredtoPlus4'],
        "transferredtoReferredBy" => [0, 'transferredtoReferredBy'],
        "transferredtoSalutation" => [0, 'transferredtoSalutation'],
        "transferredtoSendMail" => [0, 'transferredtoSendMail'],
        "transferredtoState" => [0, 'transferredtoState'],
        "transferredtoTitle" => [0, 'transferredtoTitle'],
        "transferredtoPostalcode" => [0, 'transferredtoPostalcode'],
        "groups" => [0, 'animalGroups'],
        "exportAccounts" => [0, 'animalExportAccounts'],
        "pictures" => [0, 'animalPictures'],
        "videos" => [0, 'animalVideos'],
        "videoUrls" => [0, 'animalVideoUrls'],
    ];

    /**
     * Process the response with associated output object
     * @param \RescueGroups\API $api
     * @param \stdClass $data
     * @returns \RescueGroups\Objects\Animal[]
     */
    public function processResponse(\RescueGroups\API $api, $data)
    {
        if (empty($data)) return [];

        if (is_array($data) || is_object($data))
        {
            $output = [];
            foreach ($data as $object)
            {
                $output[] = new \RescueGroups\Objects\Animal($object);
            }

            return $output;
        }

        return [new \RescueGroups\Objects\Animal($data)];
    }

    /**
     * Apply request parameters to the outgoing request
     *
     * @param $parameterArray
     */
    public function applyParameters(&$parameterArray)
    {
        $this->addSearchParameters($parameterArray);
    }
}